// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_pybXIMUovUxT3BLpNt5_OCZnLEM2HQg',
    appId: '1:298418970851:web:1f127e140ee04200e6e5d6',
    messagingSenderId: '298418970851',
    projectId: 'flutterintegrar',
    authDomain: 'flutterintegrar.firebaseapp.com',
    storageBucket: 'flutterintegrar.firebasestorage.app',
    measurementId: 'G-G2DDPZDK7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDKKiHHG_7KzTvO3x8ULcpTN9yGqjVrU',
    appId: '1:298418970851:android:b33a0424acd5e3b1e6e5d6',
    messagingSenderId: '298418970851',
    projectId: 'flutterintegrar',
    storageBucket: 'flutterintegrar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm5fPyE8sofMJBDHyfj25lgtWRXSr6AqM',
    appId: '1:298418970851:ios:79c2df55a179865ce6e5d6',
    messagingSenderId: '298418970851',
    projectId: 'flutterintegrar',
    storageBucket: 'flutterintegrar.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm5fPyE8sofMJBDHyfj25lgtWRXSr6AqM',
    appId: '1:298418970851:ios:79c2df55a179865ce6e5d6',
    messagingSenderId: '298418970851',
    projectId: 'flutterintegrar',
    storageBucket: 'flutterintegrar.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_pybXIMUovUxT3BLpNt5_OCZnLEM2HQg',
    appId: '1:298418970851:web:03ca00a5c2817030e6e5d6',
    messagingSenderId: '298418970851',
    projectId: 'flutterintegrar',
    authDomain: 'flutterintegrar.firebaseapp.com',
    storageBucket: 'flutterintegrar.firebasestorage.app',
    measurementId: 'G-4BMYPC1RYN',
  );
}
